name: CI

on: [push]

jobs:
  windows-build:
    name: Windows Build
    runs-on: windows-2019
    
    steps:
      - uses: actions/checkout@v1
      - name: Install vcpkg
        run: |
          git clone https://github.com/microsoft/vcpkg.git
          cd vcpkg
          .\bootstrap-vcpkg.bat
      - name: Install dependencies
        run: |
          cd vcpkg
          .\vcpkg install imgui:x64-windows-static
          .\vcpkg install gl3w:x64-windows-static
          .\vcpkg install ms-gsl:x64-windows-static
          .\vcpkg install sdl2:x64-windows-static
          .\vcpkg install tclap:x64-windows-static
      - name: CMake
        run: |
          cd src
          mkdir build
          cd build
          cmake -DVCPKG_TARGET_TRIPLET=x64-windows-static -DCMAKE_TOOLCHAIN_FILE="..\..\vcpkg\scripts\buildsystems\vcpkg.cmake" -G "Visual Studio 16 2019" ..
      - name: Build Debug
        run: |
          cd src/build
          cmake --build . --config Debug
      - name: Build Release
        run: |
          cd src/build
          cmake --build . --config Release

  linux-build:
    name: Linux Build
    runs-on: ubuntu-18.04
    
    steps:
      - uses: actions/checkout@v1
      - name: Install vcpkg
        run: |
          git clone https://github.com/microsoft/vcpkg.git
          cd vcpkg
          ./bootstrap-vcpkg.sh
      - name: Install OpenGL
        run: sudo apt-get install libglu1-mesa-dev
      - name: Install GCC 8
        run: | # based on: https://github.com/ArkEcosystem/cpp-crypto/blob/b05116d6ab4ffe50cad53a49ca33e95ec505064f/.github/workflows/test.yml#L46
          sudo apt-add-repository -y ppa:ubuntu-toolchain-r/test
          sudo apt-get update
          sudo apt-get -y install g++-8 gcc-8
          sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-8 60 --slave /usr/bin/g++ g++ /usr/bin/g++-8
          sudo update-alternatives --config gcc
      - name: Install dependencies
        run: |
          cd vcpkg
          ./vcpkg install imgui:x64-linux
          ./vcpkg install gl3w:x64-linux
          ./vcpkg install ms-gsl:x64-linux
          ./vcpkg install sdl2:x64-linux
          ./vcpkg install tclap:x64-linux
      - name: Install dependencies failed
        if: failure()
        uses: actions/upload-artifact@v1
        with:
          name: gl3w-files
          path: /home/runner/work/chip8-interpreter/chip8-interpreter/vcpkg/buildtrees/gl3w/
      - name: CMake
        run: |
          cd src
          mkdir build
          cd build
          cmake -DVCPKG_TARGET_TRIPLET=x64-linux -DCMAKE_TOOLCHAIN_FILE="../../vcpkg/scripts/buildsystems/vcpkg.cmake" ..
      - name: Build Debug
        run: |
          cd src/build
          cmake --build . --config Debug
      - name: Build Release
        run: |
          cd src/build
          cmake --build . --config Release
