name: CI

on: [push]

jobs:
  windows-build:
    name: Windows Build
    runs-on: windows-2019
    
    steps:
      - uses: actions/checkout@v1
      - name: Install vcpkg
        run: |
          git clone https://github.com/microsoft/vcpkg.git
          cd vcpkg
          .\bootstrap-vcpkg.bat
      - name: Install dependencies
        run: |
          cd vcpkg
          .\vcpkg --triplet x64-windows-static install imgui doctest gl3w ms-gsl sdl2 tclap
      - name: CMake
        run: |
          cd src
          mkdir build
          cd build
          cmake -DVCPKG_TARGET_TRIPLET=x64-windows-static -DCMAKE_TOOLCHAIN_FILE="..\..\vcpkg\scripts\buildsystems\vcpkg.cmake" ..
      - name: Build Debug
        run: |
          cd src/build
          cmake --build . --config Debug
      - name: Run Tests Debug
        run: |
          cd src/build/bin
          .\c8-core-test
      - name: Build Release
        run: |
          cd src/build
          cmake --build . --config Release
      - name: Run Tests Release
        run: |
          cd src/build/bin
          .\c8-core-test

  linux-build:
    name: Linux Build
    runs-on: ubuntu-18.04
    
    steps:
      - uses: actions/checkout@v1
      - name: Install vcpkg
        run: |
          git clone https://github.com/microsoft/vcpkg.git
          cd vcpkg
          ./bootstrap-vcpkg.sh
      - name: Install GCC 9
        run: | # based on: https://github.com/ArkEcosystem/cpp-crypto/blob/b05116d6ab4ffe50cad53a49ca33e95ec505064f/.github/workflows/test.yml#L46
          sudo apt-add-repository -y ppa:ubuntu-toolchain-r/test
          sudo apt-get update
          sudo apt-get -y install g++-9 gcc-9
          sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-9 60 --slave /usr/bin/g++ g++ /usr/bin/g++-9
          sudo update-alternatives --config gcc
      - name: Install OpenGL
        run: sudo apt-get install libglu1-mesa-dev
      - name: Install dependencies
        run: |
          cd vcpkg
          ./vcpkg --triplet x64-linux install imgui doctest gl3w ms-gsl sdl2 tclap
      - name: CMake
        run: |
          cd src
          mkdir build
          cd build
          cmake -DVCPKG_TARGET_TRIPLET=x64-linux -DCMAKE_TOOLCHAIN_FILE="../../vcpkg/scripts/buildsystems/vcpkg.cmake" ..
      - name: Build Debug
        run: |
          cd src/build
          cmake --build . --config Debug
      - name: Run Tests Debug
        run: |
          cd src/build/bin
          ./c8-core-test
      - name: Build Release
        run: |
          cd src/build
          cmake --build . --config Release
      - name: Run Tests Release
        run: |
          cd src/build/bin
          ./c8-core-test
